name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Create Test File
        shell: powershell
        run: |
          "GitHub Runner Working $(Get-Date)" | Out-File "D:\Website\uat\test.txt"
