name: Deploy Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Frontend
        shell: powershell
        run: |
          cd Frontend
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy Frontend to IIS
        shell: powershell
        run: |
          Copy-Item "$env:GITHUB_WORKSPACE\Frontend\dist\*" "D:\Website\uat\uatrsatsang.bharatmentors.com\Frontend\dist\" -Recurse -Force

      - name: Restart Backend
        shell: powershell
        run: |
          pm2 restart backend
